import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

export default function Layout({ children, title }) {
  return (
    <div>
      <Head>
        <title>
          {title ? `${title} - eCommerce project` : 'E-Commerce project'}
        </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 items-center px-4 justify-between shadow-md fixed w-screen bg-white">
            <Link href="/" legacyBehavior>
              <a className="text-lg font-bold">Ecommerce Logo</a>
            </Link>
            <div>
              <Link href="/cart" legacyBehavior>
                <a className="p-2">Cart</a>
              </Link>
              <Link href="/cart" legacyBehavior>
                <a className="p-2">Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-16 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p className="text-sm">Copyright @ 2022 Ecommerce project</p>
        </footer>
      </div>
    </div>
  );
}
