import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-commerce project</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className="text-3xl font-bold">E-Commerce Store</h1>
      <h1 className="font-mono">Project template for e-commerce shops</h1>
    </div>
  );
}
